AWS_REGION="eu-west-3"

# Dynamically generated by TF
export MODEL_BUCKET_PROD="stg-mlflow-models-jer-mlops-zoomcamp"
export PREDICTIONS_STREAM_NAME="stg_ride_predictions-mlops-zoomcamp"
export LAMBDA_FUNCTION="stg_ride_predictions_lambda_mlops-zoomcamp"

# Normally you would get this from the model registry, now I just uploaded the model into
# 1/run_id/artifacts/model.bin
export RUN_ID="123456"


# Set new var RUN_ID in existing set of vars.
variables="{PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}, MODEL_BUCKET=${MODEL_BUCKET_PROD}, RUN_ID=${RUN_ID}}"

# https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html
aws lambda update-function-configuration --function-name ${LAMBDA_FUNCTION} --environment "Variables=${variables}"