name: mlops2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter=1.1.1
  - pandas=2.2.3
  - pyarrow=19.0.1
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - matplotlib=3.10.1
  - hyperopt==0.2.7
  - fastparquet==2024.11.0
  - boto3==1.37.13
  - pip==25.0.1
  - pip:
    - xgboost==3.0.0
    - mlflow==2.21.0